[package]
name = "tg"
version = "0.1.0-beta.8"
edition = "2021"
license = "Apache-2.0"
description = "Terminal host for the Textagram text-based diagram editor"
repository = "https://github.com/pzoln/textagram"
readme = "README.md"

[[bin]]
name = "tg"
path = "src/main.rs"
test = false

[dependencies]
arboard = "=3.2.0"
crossterm = "0.26"
ratatui = { version = "0.26", default-features = false, features = ["crossterm"] }
textagram = { path = "../textagram" }
tracing = "0.1"
